<a href="https://colab.research.google.com/github/EduardoMoraesRitter/machine-learning-introducao-a-classificacao-com-sklearn/blob/master/Primeiro_modelo_classifica%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

no primeiro passo é analizar as features ou caracteristicas (pelo longo, perna curta, faz auau)dos animais para descobril qual especie usando sklearn e algoritimos supervisionado. f(x) = y

In [0]:
porco1 = [0,1,0]
porco2 = [0,1,1]
porco3 = [1,1,0]

cao1 = [0,1,1]
cao2 = [1,0,1]
cao3 = [1,1,1]

#treino x sao os dados
treino_x = [porco1, porco2, porco3, cao1, cao2,cao3]
#o treino y sao as classes ou labels como porco = 1 cao = 0
treino_y = [1,1,1,0,0,0]

In [2]:
#usar um estimador do tipo classificador
from sklearn.svm import LinearSVC

#intaciar o modela vazio
model = LinearSVC()
#treinar o modelo com os dados e as classes
model.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [0]:
animal_misterioso = [1,1,1]

In [4]:
model.predict(animal_misterioso)

ValueError: ignored

In [5]:
#o predict espera um array de duas dimencoes ValueError: Expected 2D array, got 1D array instead
model.predict([animal_misterioso])
#entao ele previu que é um cão

array([0])

In [0]:
misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

teste_x = [misterio1, misterio2, misterio3]
#primeiro precisa de um classe de teste
teste_y = [0, 1, 1]

In [7]:
previsoes = model.predict(teste_x)
print(previsoes)

[0 1 0]


##calcular taxa de acerto

In [8]:
#sklearn usa uma biblioteca numpy por traz
#a precisao restorna um array do numpy
print(type(previsoes))
#a lista que montamos é so um lista simples
print(type(teste_y))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
#o numpy ja facilita a conversao dos tipos
previsoes == teste_y

array([ True,  True, False])

In [10]:
#quantidade de acertos
corretos = (previsoes == teste_y).sum()
corretos

2

In [13]:
#total de itens analizado
total = len(teste_x)
total

3

In [14]:
#taxa de acertos é quantidade corretos dividido pelo total
taxa_acertos = corretos/total
print('Taxa de Acertos: ', taxa_acertos)
print('Taxa de Acertos: ', taxa_acertos * 100)

Taxa de Acertos:  0.6666666666666666
Taxa de Acertos:  66.66666666666666


In [18]:
#na biblioteca ta tem pronto a taxa de acertos ou nota de acerto(accuracy ou acuracia) | quanto vc acertou
#https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

from sklearn.metrics import accuracy_score

taxa_acerto = accuracy_score(teste_y, previsoes)
#ponto flutuante para deixar duas casas decimais
print('Taxa de Acertos: %.2f' % (taxa_acerto * 100))

Taxa de Acertos: 66.67
